# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Pydantic v2 models for building CQL2 JSON filters."""

from cql2json_pydantic.__about__ import __version__
from cql2json_pydantic.models import (
    Accenti,
    AndOrExpression,
    AndOrExpressionOp,
    ArithmeticExpression,
    ArithmeticExpressionOp,
    ArrayPredicate,
    ArrayPredicateOp,
    BboxLiteral,
    BinaryComparisonPredicate,
    BinaryComparisonPredicateOp,
    Casei,
    ComparisonPredicate,
    Coordinate,
    Coordinate1,
    Coordinate1Item,
    Coordinate2,
    Coordinate3,
    Coordinate3Item,
    Coordinate4,
    Coordinate4Item,
    DateInstant,
    DateString,
    FunctionRef,
    Geometrycollection,
    IntervalInstance,
    IsBetweenPredicate,
    IsInListPredicate,
    IsLikePredicate,
    IsNullPredicate,
    Linestring,
    Multilinestring,
    Multipoint,
    Multipolygon,
    NotExpression,
    PatternExpression1,
    PatternExpression2,
    Point,
    Polygon,
    PropertyRef,
    SpatialPredicate,
    SpatialPredicateOp,
    TemporalPredicate,
    TemporalPredicateOp,
    TimestampInstant,
    TimestampString,
)

__all__ = [
    "Accenti",
    "AndOrExpression",
    "AndOrExpressionOp",
    "ArithmeticExpression",
    "ArithmeticExpressionOp",
    "ArrayPredicate",
    "ArrayPredicateOp",
    "BboxLiteral",
    "BinaryComparisonPredicate",
    "BinaryComparisonPredicateOp",
    "Casei",
    "ComparisonPredicate",
    "Coordinate",
    "Coordinate1",
    "Coordinate1Item",
    "Coordinate2",
    "Coordinate3",
    "Coordinate3Item",
    "Coordinate4",
    "Coordinate4Item",
    "DateInstant",
    "DateString",
    "FunctionRef",
    "Geometrycollection",
    "IntervalInstance",
    "IsBetweenPredicate",
    "IsInListPredicate",
    "IsLikePredicate",
    "IsNullPredicate",
    "Linestring",
    "Multilinestring",
    "Multipoint",
    "Multipolygon",
    "NotExpression",
    "PatternExpression1",
    "PatternExpression2",
    "Point",
    "Polygon",
    "PropertyRef",
    "SpatialPredicate",
    "SpatialPredicateOp",
    "TemporalPredicate",
    "TemporalPredicateOp",
    "TimestampInstant",
    "TimestampString",
    "__version__",
]
