# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# generated by datamodel-codegen:
#   filename:  cql2json.yaml
#   timestamp: 2026-10-09T13:48:54+00:00

from __future__ import annotations

from enum import Enum
from typing import TYPE_CHECKING, Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel
from pydantic_core import PydanticUndefined, PydanticUndefinedType

if TYPE_CHECKING:
    from collections.abc import Sequence


class AndOrExpressionOp(Enum):
    AND = "and"
    OR = "or"


class BinaryComparisonPredicateOp(Enum):
    EQUAL = "="
    NOT_EQUAL = "<>"
    LESS_THAN = "<"
    GREATER_THAN = ">"
    LESS_THAN_OR_EQUAL = "<="
    GREATER_THAN_OR_EQUAL = ">="


class SpatialPredicateOp(Enum):
    S_CONTAINS = "s_contains"
    S_CROSSES = "s_crosses"
    S_DISJOINT = "s_disjoint"
    S_EQUALS = "s_equals"
    S_INTERSECTS = "s_intersects"
    S_OVERLAPS = "s_overlaps"
    S_TOUCHES = "s_touches"
    S_WITHIN = "s_within"


class TemporalPredicateOp(Enum):
    T_AFTER = "t_after"
    T_BEFORE = "t_before"
    T_CONTAINS = "t_contains"
    T_DISJOINT = "t_disjoint"
    T_DURING = "t_during"
    T_EQUALS = "t_equals"
    T_FINISHED_BY = "t_finishedBy"
    T_FINISHES = "t_finishes"
    T_INTERSECTS = "t_intersects"
    T_MEETS = "t_meets"
    T_MET_BY = "t_metBy"
    T_OVERLAPPED_BY = "t_overlappedBy"
    T_OVERLAPS = "t_overlaps"
    T_STARTED_BY = "t_startedBy"
    T_STARTS = "t_starts"


class ArrayPredicateOp(Enum):
    A_CONTAINED_BY = "a_containedBy"
    A_CONTAINS = "a_contains"
    A_EQUALS = "a_equals"
    A_OVERLAPS = "a_overlaps"


class ArithmeticExpressionOp(Enum):
    ADD = "+"
    SUBTRACT = "-"
    MULTIPLY = "*"
    DIVIDE = "/"
    POWER = "^"
    MODULO = "%"
    INTEGER_DIVIDE = "div"


class PropertyRef(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    property: str


class Point(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["Point"] = "Point"
    coordinates: Annotated[list[float], Field(min_length=2)]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[float] | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class LinestringCoordinate(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Linestring(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["LineString"] = "LineString"
    coordinates: Annotated[list[LinestringCoordinate], Field(min_length=2)]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[LinestringCoordinate | Sequence[float]]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class PolygonCoordinateItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class PolygonCoordinate(RootModel[list[PolygonCoordinateItem]]):
    root: Annotated[list[PolygonCoordinateItem], Field(min_length=4)]


class Polygon(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["Polygon"] = "Polygon"
    coordinates: list[PolygonCoordinate]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[PolygonCoordinate | Sequence[PolygonCoordinateItem | Sequence[float]]]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class MultipointCoordinate(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class Multipoint(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiPoint"] = "MultiPoint"
    coordinates: list[MultipointCoordinate]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[MultipointCoordinate | Sequence[float]]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class MultilinestringCoordinateItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class MultilinestringCoordinate(RootModel[list[MultilinestringCoordinateItem]]):
    root: Annotated[list[MultilinestringCoordinateItem], Field(min_length=2)]


class Multilinestring(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiLineString"] = "MultiLineString"
    coordinates: list[MultilinestringCoordinate]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[
            MultilinestringCoordinate | Sequence[MultilinestringCoordinateItem | Sequence[float]]
        ]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class MultipolygonCoordinateItem(RootModel[list[float]]):
    root: Annotated[list[float], Field(min_length=2)]


class MultipolygonCoordinate(RootModel[list[MultipolygonCoordinateItem]]):
    root: Annotated[list[MultipolygonCoordinateItem], Field(min_length=4)]


class Multipolygon(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["MultiPolygon"] = "MultiPolygon"
    coordinates: list[list[MultipolygonCoordinate]]
    bbox: Annotated[list[float] | None, Field(min_length=4)] = None

    def __init__(
        self,
        coordinates: Sequence[
            Sequence[
                MultipolygonCoordinate | Sequence[MultipolygonCoordinateItem | Sequence[float]]
            ]
        ]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword coordinates.

        Args:
            coordinates: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if coordinates is not PydanticUndefined:
            data["coordinates"] = coordinates
        super().__init__(**data)


class Geometrycollection(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    type: Literal["GeometryCollection"] = "GeometryCollection"
    geometries: Annotated[
        list[Point | Linestring | Polygon | Multipoint | Multilinestring | Multipolygon],
        Field(min_length=2),
    ]

    def __init__(
        self,
        geometries: Sequence[
            Point | Linestring | Polygon | Multipoint | Multilinestring | Multipolygon
        ]
        | PydanticUndefinedType = PydanticUndefined,
        **data: object,
    ) -> None:
        """Build a geometry from positional or keyword geometries.

        Args:
            geometries: Geometry members in GeoJSON order, as lists or tuples.
            **data: Additional GeoJSON fields, validated by the generated model.

        Raises:
            pydantic.ValidationError: If the geometry violates the schema constraints.
        """
        if geometries is not PydanticUndefined:
            data["geometries"] = geometries
        super().__init__(**data)


class DateString(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")]


class TimestampString(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$")]


class BboxLiteral(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    bbox: list[float]


class DateInstant(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    date: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")]


class TimestampInstant(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    timestamp: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$")
    ]


class Accenti(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["accenti"] = "accenti"
    args: Annotated[
        list[PropertyRef | FunctionRef | Casei | Accenti | str], Field(max_length=1, min_length=1)
    ]


class AndOrExpression(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: AndOrExpressionOp
    args: Annotated[
        list[
            AndOrExpression
            | NotExpression
            | BinaryComparisonPredicate
            | IsLikePredicate
            | IsBetweenPredicate
            | IsInListPredicate
            | IsNullPredicate
            | SpatialPredicate
            | TemporalPredicate
            | ArrayPredicate
            | FunctionRef
            | bool
        ],
        Field(min_length=2),
    ]


class ArithmeticExpression(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: ArithmeticExpressionOp
    args: Annotated[
        list[ArithmeticExpression | PropertyRef | FunctionRef | float],
        Field(max_length=2, min_length=2),
    ]


class Array(
    RootModel[
        list[
            Union[
                "Casei",
                Accenti,
                str,
                ArithmeticExpression,
                float,
                AndOrExpression,
                "NotExpression",
                "BinaryComparisonPredicate",
                "IsLikePredicate",
                "IsBetweenPredicate",
                "IsInListPredicate",
                "IsNullPredicate",
                "SpatialPredicate",
                "TemporalPredicate",
                "ArrayPredicate",
                "FunctionRef",
                bool,
                Point,
                Linestring,
                Polygon,
                Multipoint,
                Multilinestring,
                Multipolygon,
                Geometrycollection,
                BboxLiteral,
                DateInstant,
                TimestampInstant,
                "IntervalInstance",
                "Array",
                PropertyRef,
            ]
        ]
    ]
):
    """
    A recursive CQL2 array literal.
    """

    root: Annotated[
        list[
            Casei
            | Accenti
            | str
            | ArithmeticExpression
            | float
            | AndOrExpression
            | NotExpression
            | BinaryComparisonPredicate
            | IsLikePredicate
            | IsBetweenPredicate
            | IsInListPredicate
            | IsNullPredicate
            | SpatialPredicate
            | TemporalPredicate
            | ArrayPredicate
            | FunctionRef
            | bool
            | Point
            | Linestring
            | Polygon
            | Multipoint
            | Multilinestring
            | Multipolygon
            | Geometrycollection
            | BboxLiteral
            | DateInstant
            | TimestampInstant
            | IntervalInstance
            | Array
            | PropertyRef
        ],
        Field(min_length=0),
    ]
    """
    A recursive CQL2 array literal.
    """


class ArrayPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: ArrayPredicateOp
    args: Annotated[
        list[
            list[
                Casei
                | Accenti
                | str
                | ArithmeticExpression
                | float
                | AndOrExpression
                | NotExpression
                | BinaryComparisonPredicate
                | IsLikePredicate
                | IsBetweenPredicate
                | IsInListPredicate
                | IsNullPredicate
                | SpatialPredicate
                | TemporalPredicate
                | ArrayPredicate
                | FunctionRef
                | bool
                | Point
                | Linestring
                | Polygon
                | Multipoint
                | Multilinestring
                | Multipolygon
                | Geometrycollection
                | BboxLiteral
                | DateInstant
                | TimestampInstant
                | IntervalInstance
                | Array
                | PropertyRef
            ]
            | PropertyRef
            | FunctionRef
        ],
        Field(max_length=2, min_length=2),
    ]


class BinaryComparisonPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: BinaryComparisonPredicateOp
    args: Annotated[
        list[
            Casei
            | Accenti
            | str
            | ArithmeticExpression
            | float
            | bool
            | DateInstant
            | TimestampInstant
            | FunctionRef
            | PropertyRef
        ],
        Field(max_length=2, min_length=2),
    ]


class Casei(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["casei"] = "casei"
    args: Annotated[
        list[PropertyRef | FunctionRef | Casei | Accenti | str], Field(max_length=1, min_length=1)
    ]


class ComparisonPredicate(
    RootModel[
        Union[
            BinaryComparisonPredicate,
            "IsLikePredicate",
            "IsBetweenPredicate",
            "IsInListPredicate",
            "IsNullPredicate",
        ]
    ]
):
    root: (
        BinaryComparisonPredicate
        | IsLikePredicate
        | IsBetweenPredicate
        | IsInListPredicate
        | IsNullPredicate
    )


class FunctionRef(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: str
    args: list[
        list[
            Casei
            | Accenti
            | str
            | ArithmeticExpression
            | float
            | AndOrExpression
            | NotExpression
            | BinaryComparisonPredicate
            | IsLikePredicate
            | IsBetweenPredicate
            | IsInListPredicate
            | IsNullPredicate
            | SpatialPredicate
            | TemporalPredicate
            | ArrayPredicate
            | FunctionRef
            | bool
            | Point
            | Linestring
            | Polygon
            | Multipoint
            | Multilinestring
            | Multipolygon
            | Geometrycollection
            | BboxLiteral
            | DateInstant
            | TimestampInstant
            | IntervalInstance
            | Array
            | PropertyRef
        ]
        | PropertyRef
        | Casei
        | Accenti
        | str
        | ArithmeticExpression
        | float
        | AndOrExpression
        | NotExpression
        | BinaryComparisonPredicate
        | IsLikePredicate
        | IsBetweenPredicate
        | IsInListPredicate
        | IsNullPredicate
        | SpatialPredicate
        | TemporalPredicate
        | ArrayPredicate
        | FunctionRef
        | bool
        | BboxLiteral
        | Point
        | Linestring
        | Polygon
        | Multipoint
        | Multilinestring
        | Multipolygon
        | Geometrycollection
        | IntervalInstance
    ]


class IntervalInstance(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    interval: Annotated[
        list[Literal[".."] | PropertyRef | FunctionRef | DateString | TimestampString],
        Field(max_length=2, min_length=2),
    ]


class IsBetweenPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["between"] = "between"
    args: Annotated[
        list[PropertyRef | FunctionRef | ArithmeticExpression | float],
        Field(max_length=3, min_length=3),
    ]


class IsInListPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["in"] = "in"
    args: tuple[
        Casei
        | Accenti
        | str
        | ArithmeticExpression
        | float
        | bool
        | DateInstant
        | TimestampInstant
        | FunctionRef
        | PropertyRef,
        list[
            Casei
            | Accenti
            | str
            | ArithmeticExpression
            | float
            | bool
            | DateInstant
            | TimestampInstant
            | FunctionRef
            | PropertyRef
        ],
    ]


class IsLikePredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["like"] = "like"
    args: tuple[
        PropertyRef | FunctionRef | Casei | Accenti | str,
        PatternExpression1 | PatternExpression2 | str,
    ]


class IsNullPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["isNull"] = "isNull"
    args: Annotated[
        list[
            PropertyRef
            | Casei
            | Accenti
            | str
            | ArithmeticExpression
            | float
            | AndOrExpression
            | NotExpression
            | BinaryComparisonPredicate
            | IsLikePredicate
            | IsBetweenPredicate
            | IsInListPredicate
            | IsNullPredicate
            | SpatialPredicate
            | TemporalPredicate
            | ArrayPredicate
            | FunctionRef
            | bool
            | BboxLiteral
            | Point
            | Linestring
            | Polygon
            | Multipoint
            | Multilinestring
            | Multipolygon
            | Geometrycollection
            | IntervalInstance
        ],
        Field(max_length=1, min_length=1),
    ]


class NotExpression(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["not"] = "not"
    args: Annotated[
        list[
            AndOrExpression
            | NotExpression
            | BinaryComparisonPredicate
            | IsLikePredicate
            | IsBetweenPredicate
            | IsInListPredicate
            | IsNullPredicate
            | SpatialPredicate
            | TemporalPredicate
            | ArrayPredicate
            | FunctionRef
            | bool
        ],
        Field(max_length=1, min_length=1),
    ]


class PatternExpression1(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["casei"] = "casei"
    args: Annotated[
        list[PatternExpression1 | PatternExpression2 | str], Field(max_length=1, min_length=1)
    ]


class PatternExpression2(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: Literal["accenti"] = "accenti"
    args: Annotated[
        list[PatternExpression1 | PatternExpression2 | str], Field(max_length=1, min_length=1)
    ]


class SpatialPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: SpatialPredicateOp
    args: Annotated[
        list[
            PropertyRef
            | FunctionRef
            | BboxLiteral
            | Point
            | Linestring
            | Polygon
            | Multipoint
            | Multilinestring
            | Multipolygon
            | Geometrycollection
        ],
        Field(max_length=2, min_length=2),
    ]


class TemporalPredicate(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    op: TemporalPredicateOp
    args: Annotated[
        list[PropertyRef | FunctionRef | IntervalInstance | DateInstant | TimestampInstant],
        Field(max_length=2, min_length=2),
    ]


Accenti.model_rebuild()
ArithmeticExpression.model_rebuild()
Array.model_rebuild()
BinaryComparisonPredicate.model_rebuild()
Casei.model_rebuild()
ComparisonPredicate.model_rebuild()
FunctionRef.model_rebuild()
